# ELT Posts Wordpress

base de dados:
- dados dos posts wordpress (pre-migração)
- dados dos posts wix (pós-migração)

Como organizar os dados de forma que facilite a migração e tratamento entre as duas plataformas?

- usar duckdb para compilar os dados relacionado a cada post
- importar dados brutos do wordpress pelo csv
- importar dados atuais do wix
- criar colunar auxiliares para tratamentos


checklist:
- Decidir como executar processo de etl
    - qual estrutura de dados vai ser usada
        - tratamento de dados: duck e dict
        - armazenamento de dados: duck
    - qual Limites de transação de cada api?

- download de posts wix: Completo
    - listar todos posts_id's: completo
    - baixar todos os posts: completo

- converter posts para dict: feito
- coletar versão funcional do main com wallace: feito

- converter post html para rico_documento wix: revisar
    - tags's de titulos
    - tags's de texto
    - tag's de video
    - tag's de decoração
    - tag's de imagens
    - scripts
-

# Loads

## Imports

In [1]:
import pandas as pd
import os
import json

## Upload Dados

In [2]:
caminho_csv_wordpress = './data/pre-processing/Posts-Export-2025-July-25-1838.csv'
caminho_posts_wix = './data/posts/'
mapeamento = './data/wix_wordpress_mapping.json'


df = pd.read_csv(caminho_csv_wordpress)
df.head(10)

,ID,check de edição,Title,Content,Excerpt,Date,PostType,Coluna 1,Permalink,ImageURL,...,AuthorLastName,Slug,Format,Template,Parent,ParentSlug,Order,CommentStatus,PingStatus,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,debito-ou-credito,NaN,NaN,NaN,NaN,NaN,open,open,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,NaN,NaN,NaN,NaN,NaN,open,open,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,NaN,NaN,NaN,NaN,NaN,open,open,2018-07-12
5,47,False,NFCe: posso emitir na minha impressora fiscal?,"<span style=""font-weight: 400;"">O ECF - Emisso...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/legislacao/nfce-...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,nfce-posso-emitir-na-minha-impressora-fiscal,NaN,NaN,NaN,NaN,NaN,open,open,2018-03-13
6,51,False,NF-e e NFC-e: sou obrigado emitir?,"<span style=""font-weight: 400;"">Você abriu sua...",NaN,2018-03-01,post,NaN,https://otimizeseunegocio.com/legislacao/nf-e-...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,nf-e-e-nfc-e-sou-obrigado-emitir,NaN,NaN,NaN,NaN,NaN,open,open,2019-05-10
7,89,False,Como emitir uma nota fiscal eletrônica utiliza...,"<iframe src=""https://www.youtube.com/embed/KdK...",NaN,2018-03-15,post,NaN,https://otimizeseunegocio.com/legislacao/como-...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,como-emitir-uma-nota-fiscal-eletronica-utiliza...,NaN,NaN,NaN,NaN,NaN,open,open,2018-03-17
8,94,False,[Planilha Financeira] Se você cuida bem das su...,"<iframe src=""https://www.youtube.com/embed/ta_...",NaN,2018-03-17,post,NaN,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,movimento-de-caixa-planilha-gratis,NaN,NaN,NaN,NaN,NaN,open,open,2018-03-17
9,98,False,Como instalar o Emissor Gratuito?,<h4>Antes que você veja sobre o emisssor gratu...,NaN,2018-03-24,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,como-instalar-o-emissor-gratuito,NaN,NaN,NaN,NaN,NaN,open,open,2020-09-30

# Tratamentos/Tranforms

## planejamento dos tratamentos

## Limpeza

- filtra posts publicos
- Mapear id's wix-wordpress
- remover colunas desnecessarias
-

### Mapeamento Wordpress-Wix

In [3]:
# Renomear colunas do DataFrame

# 'coluna 1' -> 'ID_wix'
# 'ID' -> 'ID_Wordpress'

if 'Coluna 1' in df.columns and 'ID' in df.columns:
    df.rename(columns={'Coluna 1': 'ID_wix', 'ID': 'ID_Wordpress'}, inplace=True)

df.head()

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,PostType,ID_wix,Permalink,ImageURL,...,AuthorLastName,Slug,Format,Template,Parent,ParentSlug,Order,CommentStatus,PingStatus,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,debito-ou-credito,NaN,NaN,NaN,NaN,NaN,open,open,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,NaN,NaN,NaN,NaN,NaN,open,open,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,NaN,NaN,NaN,NaN,NaN,open,open,2018-07-12

In [4]:
df1 = df

In [6]:
# Diretório onde os arquivos JSON estão localizados
posts_dir = './data/posts/' # Corrected path to posts directory
mapeamento_path = './data/wix_wordpress_mapping.json' # Corrected path to mapping file

# Load the mapping from the JSON file
try:
    with open(mapeamento_path, 'r') as f:
        wix_wordpress_mapping = json.load(f)
except (IOError, json.JSONDecodeError) as e:
    print(f"Erro ao carregar o arquivo de mapeamento {mapeamento_path}: {e}")
    wix_wordpress_mapping = {} # Initialize as empty dict if error occurs

def find_and_update_wix_id(row):
    id_wordpress = str(row['ID_Wordpress']) # Convert to string to match keys in mapping
    # Look up the ID_wix in the mapping
    wix_id = wix_wordpress_mapping.get(id_wordpress)
    return wix_id

# Iterar sobre cada linha do DataFrame e atualizar a coluna 'ID_wix'
df1['ID_wix'] = df1.apply(find_and_update_wix_id, axis=1)

print("DataFrame atualizado:")
display(df1.head())

DataFrame atualizado:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,PostType,ID_wix,Permalink,ImageURL,...,AuthorLastName,Slug,Format,Template,Parent,ParentSlug,Order,CommentStatus,PingStatus,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,post,7bfef44e-8236-491b-a067-8899f099cab9,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,debito-ou-credito,NaN,NaN,NaN,NaN,NaN,open,open,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,post,6fb1b5f0-206a-43df-8780-0791e5888748,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,post,f85b6f54-eccb-4c9f-8596-b834393e8dcc,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,post,d1eeb586-be43-416b-b4d1-6e2209ce970e,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,NaN,NaN,NaN,NaN,NaN,open,open,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,post,a1cdc880-389a-4b99-9584-bf9574513fcd,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,NaN,NaN,NaN,NaN,NaN,open,open,2018-07-12

### Eliminação de Colunas desnecessarias

In [6]:
df2 = df1

In [7]:
# Identify columns with only empty values or a single unique value
cols_to_drop_identified = []
for col in df2.columns:
    # Drop NaN values before checking for unique values
    unique_values = df2[col].dropna().unique()
    if len(unique_values) <= 1:
        cols_to_drop_identified.append(col)

print("Colunas com apenas campos vazios ou um único valor:")
for col in cols_to_drop_identified:
    print(f"- {col}")

Colunas com apenas campos vazios ou um único valor:
- Excerpt
- PostType
- ID_wix
- AttachmentURL
- _rdscriptcontenttop
- _rdscriptcontentbottom
- _rdscriptcontentinhead
- _rdscriptcontentinfooter
- _wp_page_template
- site_sidebar_layout
- site_content_layout
- theme_transparent_header_meta
- _elementor_edit_mode
- _elementor_template_type
- _elementor_pro_version
- _wpas_done_all
- _pingme
- _encloseme
- ast_site_content_layout
- site_content_style
- site_sidebar_style
- _elementor_controls_usage
- amp_status
- _et_pb_use_builder
- _et_pb_old_content
- _jetpack_memberships_contains_paid_content
- Format
- Template
- Parent
- ParentSlug
- Order
- CommentStatus
- PingStatus

In [ ]:
colunas_para_remover = ['Format', 'Template', 'Parent', 'ParentSlug', 'CommentStatus', 'PingStatus', 'PostType', 'AttachmentURL', '_rdscriptcontenttop', '_rdscriptcontentbottom', '_rdscriptcontentinhead',
                        '_rdscriptcontentinfooter', '_wp_page_template', 'site_sidebar_layout', 'site_content_layout', 'theme_transparent_header_meta', '_elementor_edit_mode', '_elementor_template_type', '_elementor_pro_version', '_wpas_done_all', '_pingme', '_encloseme', 'ast_site_content_layout', 'site_content_style', 'site_sidebar_style', '_elementor_controls_usage', 'amp_status', '_et_pb_use_builder', '_et_pb_old_content', '_jetpack_memberships_contains_paid_content', 'Order']

# Filter out columns that do not exist in the DataFrame
cols_to_drop_existing = [col for col in colunas_para_remover if col in df2.columns]

df2 = df2.drop(columns=cols_to_drop_existing)
print("DataFrame após remover colunas irrelevantes:")
display(df2.head())

DataFrame após remover colunas irrelevantes:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cash only|Ingredientes de uma pizza,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Multas são caras|Nazaré confusa,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,Problemas com o sistema,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,Certificado digital|Certificado digital e token,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,2018-07-12

### Remover posts Nao-Publicados

In [9]:
# Filter posts where status is not 'publish'
posts_not_published = df2[df2['Status'] != 'publish']

print("Posts com status diferente de 'publish':")
display(posts_not_published)

Posts com status diferente de 'publish':

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
52,629,False,[Dúvida] O MEI precisa de Contador?,"Afinal, o Microempreendedor Individual precisa...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=629,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2019-10-21
67,727,False,Como emitir uma Nota Fiscal no emissor gratuit...,"<img class=""alignnone wp-image-417 aligncenter...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=727,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2020-05-14
73,803,False,Como desabilitar um produto no Easygestor,Vá no Aplicativo de compras\n\n&nbsp;,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=803,NaN,NaN,...,NaN,NaN,draft,4,vitor,vitor@ebi.com.br,Vitor,Alves,NaN,2020-08-04
76,896,False,Descubra como Agendar mensagens pela Whatsapp,Quem é,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=896,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2020-09-08
83,1024,False,Tabela do Simples Nacional Atualizada 2020,NaN,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1024,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2020-11-03
91,1682,False,Tabela De Atividades Permitidas MEI 2021,<h4>Se você acabou de se tornar <strong>MEI</s...,Descubra aqui quais atividades o MEI pode exercer,2021-05-06,None,https://otimizeseunegocio.com/legislacao/tabel...,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,private,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,tabela-de-atividades-permitidadas-mei-2021,2021-09-08
97,1812,False,COMO ABRIR UM MEI GRÁTIS,"<span style=""font-weight: 400;"">Abrir e gerenc...",NaN,2021-12-21,None,https://otimizeseunegocio.com/?p=1812,https://otimizeseunegocio.com/wp-content/uploa...,MEI-Microempreendedor-Individual,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-03-23
106,1960,False,Teste,NaN,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1960,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-08-16
107,1962,False,CLT e MEI: é possivel ser MEI e ter a carteira...,NaN,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1962,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-08-17
111,1992,False,COMPRA DE SEGUIDORES É UM RISCO?,"<span style=""font-weight: 400"">Parece uma ótim...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1992,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,1970-01-01
120,2159,False,CERTIFICADO DIGITAL: PRINCIPAIS RISCOS E CUIDA...,"<span style=""font-weight: 400""><img class=""ali...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=2159,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-10-27
130,2333,False,Recuperando Arquivos do PC e Pendrive: Um Guia...,&nbsp;\n\nEm um mundo onde a tecnologia desemp...,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=2333,NaN,NaN,...,NaN,NaN,draft,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,NaN,2023-08-25
137,2398,False,Curso de Marketing Digital com Super desconto ...,O Canal Otimize seu Negócio está chegando a 20...,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=2398,https://otimizeseunegocio.com/wp-content/uploa...,Imagem do WhatsApp de 2023-09-19 à(s) 12.51.49,...,NaN,NaN,draft,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,NaN,2023-09-19
226,3114,False,Totem Especialista Belém,"<script>!function(window){const host=""https://...",NaN,2024-10-02,None,https://otimizeseunegocio.com/?p=3114,NaN,NaN,...,NaN,NaN,draft,4,vitor,vitor@ebi.com.br,Vitor,Alves,totem-especialista-belem,2024-10-02

In [10]:
# Remove posts with status other than 'publish' from df2
df2 = df2.drop(posts_not_published.index)

print("DataFrame df2 após remover posts não publicados:")
display(df2.head())
print(f"\nNúmero de linhas em df2 após a remoção: {len(df2)}")

DataFrame df2 após remover posts não publicados:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cash only|Ingredientes de uma pizza,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Multas são caras|Nazaré confusa,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,Problemas com o sistema,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,Certificado digital|Certificado digital e token,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,2018-07-12

Número de linhas em df2 após a remoção: 250

In [11]:
print(f"Número de colunas em df2: {len(df2.columns)}")
print("\nColunas em df2:")
for col in df2.columns:
    print(f"- {col}")

Número de colunas em df2: 37

Colunas em df2:
- ID_Wordpress
- check de edição
- Title
- Content
- Excerpt
- Date
- ID_wix
- Permalink
- ImageURL
- ImageTitle
- ImageCaption
- ImageDescription
- ImageAltText
- ImageFeatured
- Categorias
- Tags
- highlight
- highlight_list
- _jetpack_related_posts_cache
- _last_editor_used_jetpack
- _elementor_version
- ekit_post_views_count
- astra_migrate_meta_layouts
- _elementor_data
- dsq_thread_id
- _elementor_page_assets
- _wp_old_slug
- _wp_old_date
- _elementor_css
- Status
- AuthorID
- AuthorUsername
- AuthorEmail
- AuthorFirstName
- AuthorLastName
- Slug
- PostModifiedDate

In [ ]:
# Lista de colunas a serem removidas, focando em metadados de plugins, temas e cache.
# Colunas importantes para SEO e para a estrutura do WordPress foram mantidas.
colunas_para_remover = [
    # Formato e estrutura do post (geralmente não críticos para migração de blog)
    'Format', 'Template', 'Parent', 'ParentSlug', 'Order',
    'CommentStatus', 'PingStatus',

    # Scripts de plugins (ex: RD Station)
    '_rdscriptcontenttop', '_rdscriptcontentbottom', '_rdscriptcontentinhead',
    '_rdscriptcontentinfooter',

    # Metadados de Tema (Astra, Divi, etc.)
    '_wp_page_template', 'site_sidebar_layout', 'site_content_layout',
    'theme_transparent_header_meta', 'ast_site_content_layout',
    'site_content_style', 'site_sidebar_style', 'astra_migrate_meta_layouts',
    '_et_pb_use_builder', '_et_pb_old_content',

    # Metadados e cache de Plugins (Elementor, Jetpack, etc.)
    '_elementor_edit_mode', '_elementor_template_type',
    '_elementor_pro_version', '_elementor_version', '_elementor_controls_usage',
    '_elementor_page_assets', '_elementor_css','_last_editor_used_jetpack',
    '_jetpack_memberships_contains_paid_content',
    'ekit_post_views_count', '_wpas_done_all', '_pingme', '_encloseme',

    # Metadados que podem ou não ser úteis (geralmente dispensáveis)
    'AttachmentURL', 'amp_status'
]

# Filtra a lista para incluir apenas colunas que realmente existem no DataFrame
# Isso evita erros caso uma coluna da lista não esteja presente no seu arquivo CSV
cols_to_drop_existing = [col for col in colunas_para_remover if col in df2.columns]

# Remove as colunas selecionadas do DataFrame
df2 = df2.drop(columns=cols_to_drop_existing)

print("DataFrame após remover colunas irrelevantes para SEO e migração:")
# Corrigido para exibir o DataFrame que foi modificado (df2)
display(df2.head())

DataFrame após remover colunas irrelevantes para SEO e migração:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_slug,_wp_old_date,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cash only|Ingredientes de uma pizza,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Multas são caras|Nazaré confusa,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,Problemas com o sistema,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,Certificado digital|Certificado digital e token,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,2018-07-12

## Analise de dados

### análise exploratória da coluna 'Content'
-  Para encontrar padrões, podemos considerar as seguintes hipóteses:

*   **Padrões de Títulos e Subtítulos:** 
    - Existem padrões no uso de tags de título (`<h1>`, `<h2>`, etc.) dentro do conteúdo que podem indicar a estrutura ou o tipo de post (ex: tutoriais, listas, artigos informativos)?

*   **Presença e Tipo de Mídia:** 
    - A inclusão de imagens (`<img>`), vídeos (`<iframe>` ou tags de vídeo) ou outros elementos multimídia varia entre os posts? A frequência ou o tipo de mídia pode ser um indicador de categoria ou formato de conteúdo.

*   **Uso de Listas:** 
    - Posts que utilizam listas (`<ul>`, `<ol>`) com frequência podem pertencer a categorias específicas (ex: "5 dicas para...", "Checklist de...").

*   **Presença de Links Externos/Internos:** 
    - A quantidade ou o tipo de links presentes no conteúdo pode indicar se o post é mais voltado para informação externa, referência a outros posts do blog, ou chamadas para ação.

*   **Estrutura de Parágrafos e Formatação de Texto:** 
    - O tamanho médio dos parágrafos, o uso de negrito (`<strong>` ou `<b>`), itálico (`<em>` ou `<i>`) ou blocos de citação (`<blockquote>`) podem revelar estilos de escrita associados a diferentes tipos de conteúdo.

*   **Presença de Shortcodes ou Elementos Específicos do WordPress:** 
    - Existem shortcodes específicos ou estruturas de código HTML que são recorrentes em certos grupos de posts (ex: shortcodes de plugins, embeds específicos)?

*   **Comprimento do Conteúdo:** 
    - O número total de caracteres ou palavras no conteúdo HTML pode ser um fator para agrupar posts (ex: posts curtos de notícia vs. artigos longos e detalhados).

*   **Padrões de Assinatura ou Chamada para Ação:** 
    - A presença de blocos de texto repetidos no final dos posts (assinaturas de autor, chamadas para inscrição, links para redes sociais) pode ajudar a identificar posts de determinados autores ou campanhas.

## iframe

In [16]:
df3 = df2

In [ ]:
from bs4 import BeautifulSoup
import pandas as pd

# Filter posts that contain <iframe> tags in the 'Content' column
posts_with_iframe = df3[df3['Content'].str.contains('<iframe', na=False)].copy()

# Get the indices of posts with iframes
indices_with_iframe = posts_with_iframe.index

# Filter df3 to exclude these indices
posts_without_iframe_df = df3.drop(indices_with_iframe)


# Create an empty list to store the extracted data for iframes
iframe_data = []

# Iterate through the filtered posts to extract iframe data
for index, row in posts_with_iframe.iterrows():
    content = row['Content']
    soup = BeautifulSoup(content, 'html.parser')
    iframes = soup.find_all('iframe')

    # Extract the src attribute (link) from each iframe
    for iframe in iframes:
        iframe_link = iframe.get('src')
        if iframe_link:  # Only add if a link is found
            iframe_data.append({
                'ID_wix': row['ID_wix'],
                'Title': row['Title'],
                'iframe_link': iframe_link,
                'Content': content # Include the full content if needed for context
            })

# Create a new DataFrame from the collected iframe data
iframe_df = pd.DataFrame(iframe_data)

print("DataFrame com informações sobre posts contendo iframes:")
display(iframe_df.head())
print(f"\nNúmero de linhas no iframe_df: {len(iframe_df)}")

print(f"\nNúmero de linhas no posts_without_iframe_df: {len(posts_without_iframe_df)}")
print(f"\nNúmero de linhas no posts_with_iframe: {len(posts_with_iframe)}")

DataFrame com informações sobre posts contendo iframes:

,ID_wix,Title,iframe_link,Content
0,b7415ccf-153b-4694-9138-d428bfb57a20,Como emitir uma nota fiscal eletrônica utiliza...,https://www.youtube.com/embed/KdKKGgWAkdM,"<iframe src=""https://www.youtube.com/embed/KdK..."
1,a46acb77-d0a1-4c2d-91e8-8fcbc2b2c238,[Planilha Financeira] Se você cuida bem das su...,https://www.youtube.com/embed/ta_afyLCtWI,"<iframe src=""https://www.youtube.com/embed/ta_..."
2,68de8572-54c8-44ec-b6f3-0238c0bc2751,Como instalar o Emissor Gratuito?,https://www.youtube.com/embed/C-UD6O6GS4A,<h4>Antes que você veja sobre o emisssor gratu...
3,68de8572-54c8-44ec-b6f3-0238c0bc2751,Como instalar o Emissor Gratuito?,https://www.youtube.com/embed/GvFSJc4A0_o,<h4>Antes que você veja sobre o emisssor gratu...
4,fcfafb98-3dd4-4ebc-bf20-35154b210911,Programa para controle de estoque [GRÁTIS],https://www.youtube.com/embed/zBXQ6nn0bdM,EasyGestor é um sistema de código aberto (base...

Número de linhas no iframe_df: 77

Número de linhas no posts_without_iframe_df: 197

Número de linhas no posts_with_iframe: 53

In [ ]:
iframe_df.to_csv('iframe_df.csv', index=False)
print("DataFrame com iframe exportado para 'iframe_df.csv'")

DataFrame com iframe exportado para 'iframe_df.csv'

In [ ]:
posts_with_iframe.to_csv('posts_wordpress(iframe).csv', index=False)
print("DataFrame com iframe exportado para 'posts_wordpress(iframe).csv'")

DataFrame com iframe exportado para 'posts_wordpress(iframe).csv'

## shortcode

In [ ]:
from bs4 import BeautifulSoup
import re
import pandas as pd

# Define a regex pattern for WordPress shortcodes (more general to capture opening/closing)
# This pattern looks for anything within square brackets.
shortcode_pattern = r'\[.*?\]'

# Create an empty list to store the extracted data for shortcodes
shortcode_data = []
posts_with_shortcode_indices = []

# Iterate through all rows in df3
for index, row in df3.iterrows():
    content = row['Content']

    # Check if content is a string before processing
    if isinstance(content, str):
        soup = BeautifulSoup(content, 'html.parser')

        # Find all text nodes that might contain shortcodes
        text_nodes_with_shortcodes = soup.find_all(string=re.compile(shortcode_pattern))

        found_shortcodes_in_post = []

        for text_node in text_nodes_with_shortcodes:
            # Find all occurrences of shortcodes within the text node
            found_shortcodes = re.findall(shortcode_pattern, text_node)

            for shortcode in found_shortcodes:
                 # Identify the parent tag
                 parent_tag = text_node.parent.name if text_node.parent else None

                 # For simplicity here, we'll add each found shortcode individually.
                 # Handling paired shortcodes and their content requires more complex logic
                 # which might involve iterating through the text and checking for opening/closing pairs.
                 # This current approach extracts individual shortcode tags.
                 found_shortcodes_in_post.append({
                     'shortcode': shortcode,
                     'parent_tag': parent_tag
                 })

        if found_shortcodes_in_post:
            posts_with_shortcode_indices.append(index)
            # Store the list of extracted shortcode details for the post
            shortcode_data.append({
                'ID_wix': row['ID_wix'],
                'Title': row['Title'],
                'extracted_shortcodes': found_shortcodes_in_post,
                'Content': content # Include the full content for context
            })


# Create a new DataFrame from the collected shortcode data
shortcode_df = pd.DataFrame(shortcode_data)

# Filter df3 to exclude these indices to get posts without shortcodes
posts_without_shortcode_df = df3.drop(posts_with_shortcode_indices)

# Create a DataFrame with only the posts that contained shortcodes
posts_with_shortcode = df3.loc[posts_with_shortcode_indices].copy()


print("DataFrame com informações sobre posts contendo shortcodes:")
display(shortcode_df.head())
print(f"\nNúmero de linhas no shortcode_df: {len(shortcode_df)}")

print(f"\nNúmero de linhas no posts_without_shortcode_df: {len(posts_without_shortcode_df)}")
print(f"\nNúmero de linhas no posts_with_shortcode: {len(posts_with_shortcode)}")

DataFrame com informações sobre posts contendo shortcodes:

,ID_wix,Title,extracted_shortcodes,Content
0,6fb1b5f0-206a-43df-8780-0791e5888748,Qual o seu preço? Aprenda este método de calcu...,"[{'shortcode': '[caption id=""attachment_31"" al...","<p style=""text-align: center;""><em><strong>Est..."
1,f85b6f54-eccb-4c9f-8596-b834393e8dcc,Qual o seu preço? Parte 2: Aprenda de uma vez ...,[{'shortcode': '[100 - (Custo fixo + Custo var...,"<p style=""text-align: center;""><strong><em>Est..."
2,a1cdc880-389a-4b99-9584-bf9574513fcd,5 motivos para preferir o certificado A1 (e nã...,"[{'shortcode': '[button type=""success"" size=""l...","<h2 style=""text-align: center;"">[button type=""..."
3,68de8572-54c8-44ec-b6f3-0238c0bc2751,Como instalar o Emissor Gratuito?,"[{'shortcode': '[URGENTE]', 'parent_tag': 'spa...",<h4>Antes que você veja sobre o emisssor gratu...
4,None,10 coisas sobre NFC-e que você precisa saber (...,"[{'shortcode': '[caption id=""attachment_131"" a...","[caption id=""attachment_131"" align=""aligncente..."

Número de linhas no shortcode_df: 108

Número de linhas no posts_without_shortcode_df: 142

Número de linhas no posts_with_shortcode: 108

In [ ]:
posts_with_shortcode.to_csv('posts_wordpress(shortcode).csv', index=False)
print("DataFrame com iframe exportado para 'posts_wordpress(shortcode).csv'")
shortcode_df.to_csv('shortcode_df.csv', index=False)
print("DataFrame com iframe exportado para 'shortcode_df).csv'")

DataFrame com iframe exportado para 'shortcode_df).csv'

## scripts

In [ ]:
# Filter posts that contain <script> tags in the 'Content' column
posts_with_script = df3[df3['Content'].str.contains('<script', na=False)].copy()

# Get the indices of posts with scripts
indices_with_script = posts_with_script.index

# Filter df3 to exclude these indices
posts_without_script_df = df3.drop(indices_with_script)

# Create an empty list to store the extracted data for scripts (optional, depending on what needs to be extracted from scripts)
# For now, we'll just identify the posts, but you could extend this to extract script content or attributes if needed.
script_data = []

# Iterate through the filtered posts to identify script presence
for index, row in posts_with_script.iterrows():
    script_data.append({
        'ID_wix': row['ID_wix'],
        'Title': row['Title'],
        'Content': row['Content'] # Include the full content for context
    })

# Create a new DataFrame from the collected data
script_df = pd.DataFrame(script_data)


print("DataFrame com informações sobre posts contendo tags <script>:")
display(script_df.head())
print(f"\nNúmero de linhas no script_df: {len(script_df)}")

print(f"\nNúmero de linhas no posts_without_script_df: {len(posts_without_script_df)}")
print(f"\nNúmero de linhas no posts_with_script: {len(posts_with_script)}")

DataFrame com informações sobre posts contendo tags <script>:

,ID_wix,Title,Content
0,5ac30fef-fb06-4a76-bafa-a2f5f7da927e,Quer pagar multa? Fique atento às penalidades ...,"<span style=""font-weight: 400;"">Tem uma empres..."
1,None,10 coisas sobre NFC-e que você precisa saber (...,"[caption id=""attachment_131"" align=""aligncente..."
2,0d274d06-c14e-468e-a2e9-63f7efd57b43,"Automatizar sua empresa, sim ou não?","<img class=""aligncenter wp-image-157 size-larg..."
3,f63960d0-4854-4757-84e4-14dbd2ab3635,Pequenas empresas: entenda como o código de ba...,Se você tem uma empresa com venda direta de pr...
4,04dd6456-c7e5-4cce-93ce-5bde94d74370,MEI: descubra como emitir Nota Fiscal no seu E...,<!-- Start of easygestor Zendesk Widget script...

Número de linhas no script_df: 5

Número de linhas no posts_without_script_df: 245

Número de linhas no posts_with_script: 5

In [ ]:
# Filter df3 where 'check de edição' is True
df_check_true = df3[df3['check de edição'] == True].copy()

print("DataFrame df3 com 'check de edição' igual a True:")
display(df_check_true.head(22))
print(f"\nNúmero de linhas no df_check_true: {len(df_check_true)}")

DataFrame df3 com 'check de edição' igual a True:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_slug,_wp_old_date,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,7bfef44e-8236-491b-a067-8899f099cab9,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
243,3255,True,O Aumento no Custo do MEI em 2025: O Que Você ...,"<div class=""flex-shrink-0 flex flex-col relati...",NaN,2025-01-02,585c3445-8fa1-474f-aff4-6e7e84911b6c,https://otimizeseunegocio.com/legislacao/o-aum...,https://otimizeseunegocio.com/wp-content/uploa...,Yellow Black Graffiti Web Design YouTube Thumb...,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,o-aumento-no-custo-do-mei-em-2025-o-que-voce-p...,2025-01-02
244,3261,True,Imposto de Renda em 2025: O que Você Precisa S...,"O ano de 2025 está se aproximando, e com ele v...",NaN,2025-01-02,0864c2a9-50e3-439b-a86b-d9b3bd713992,https://otimizeseunegocio.com/legislacao/3261/,https://otimizeseunegocio.com/wp-content/uploa...,thumb imposto de renda 2025-video-janeiro-25,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,3261,2025-01-02
245,3268,True,ATENÇÃO MEI e Simples Nacional: Prazo Final em...,Se você tem uma empresa registrada como MEI (M...,NaN,2025-01-09,37d893ed-03c0-47a3-b2b2-9ad4856762ee,https://otimizeseunegocio.com/legislacao/atenc...,https://otimizeseunegocio.com/wp-content/uploa...,prazo mei 3,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,atencao-mei-e-simples-nacional-prazo-final-em-...,2025-01-09
246,3279,True,Como Fazer a Declaração Anual do MEI 2025: Gui...,Se você é <strong>Microempreendedor Individual...,NaN,2025-01-10,72b8eb75-5d88-4d04-a5c9-e22409e83742,https://otimizeseunegocio.com/legislacao/como-...,NaN,NaN,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-fazer-a-declaracao-anual-do-mei-2025-guia...,2025-01-10
247,3283,True,Como Abrir um MEI em 3 Minutos e Aproveitar Su...,Você sabia que é possível abrir uma empresa de...,NaN,2025-01-15,7a2b48b1-b74b-4d62-ab6f-0dbd8b6b1288,https://otimizeseunegocio.com/legislacao/como-...,https://otimizeseunegocio.com/wp-content/uploa...,abrir mei 1,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-abrir-um-mei-em-3-minutos-e-aproveitar-su...,2025-01-15
248,3286,True,PRAZO PARA QUITAR DÍVIDAS MEI: Última Chance p...,Se você é microempreendedor individual (MEI) e...,NaN,2025-01-16,e84c90ff-1339-43e4-82f6-429951bb30ab,https://otimizeseunegocio.com/tudo-para-mei/pr...,https://otimizeseunegocio.com/wp-content/uploa...,dívidas mei|dívidas mei,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,prazo-para-quitar-dividas-mei-ultima-chance-pa...,2025-02-27
249,3294,True,Hospedagem em Belém durante a COP30: Dicas e A...,<strong>Tudo o que você precisa saber sobre ho...,NaN,2025-01-24,4a129d22-d749-4f91-a81f-967b50cd8bef,https://otimizeseunegocio.com/inovacoes-invest...,https://otimizeseunegocio.com/wp-content/uploa...,Captura de tela 2025-01-24 190723,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,hospedagem-em-belem-durante-a-cop30-dicas-e-al...,2025-01-24
250,3301,True,Como Rastrear e Proteger Seu Celular Roubado: ...,Perder ou ter um celular roubado pode ser uma ...,NaN,2025-01-24,65309fdf-a01e-4385-967f-67422bd6c105,https://otimizeseunegocio.com/tutoriais/como-r...,https://otimizeseunegocio.com/wp-content/uploa...,Post instagram caminhão guincho carro moderno,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-rastrear-e-proteger-seu-celular-roubado-g...,2025-01-24
251,3307,True,Como Emitir Nota Fiscal Eletrônica para Pequen...,"Se você é um pequeno empresário, MEI (Microemp...",NaN,2025-01-31,09707952-9ff2-47ae-925e-183e1508cf78,https://otimizeseunegocio.com/tutoriais/como-e...,https://otimizeseunegocio.com/wp-content/uploa...,Onde investir em 2022 (YouTube Thumbnail),...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-emitir-nota-fiscal-eletronica-para-pequen...,2025-01-31
252,3312,True,Como Emitir uma Nota Fiscal de Entrada de Form...,"No universo dos negócios, a <a href=""https://i...",NaN,2025-02-05,69e1b458-1bad-4579-8812-243d6835bb3b,https://otimizeseunegocio.com/nota-fiscal/como...,https://otimizeseunegocio.com/wp-content/uploa...,maxresdefault,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-emitir-uma-nota-fiscal-de-entrada-de-form...,2025-02-05
253,3326,True,Cartão MEI: Como Adquirir e Utilizar para Impu...,"<p data-start=""99"" data-end=""514"">Se você é <s...",NaN,2025-03-25,19c6242d-6b33-4de8-ad33-e0561a3119f3,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,cartao-mei-como-adquirir-e-utilizar-para-impul...,2025-03-25
254,3329,True,Como Emitir um Cupom Fiscal (NFCe) em Segundos...,"<p data-start=""80"" data-end=""398"">Se você é mi...",NaN,2025-02-15,8cfeb36c-cea1-4284-9594-676a66c4b9e5,https://otimizeseunegocio.com/nota-fiscal/como...,https://otimizeseunegocio.com/wp-content/uploa...,Captura de tela 2025-02-15 020544|Captura de t...,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-emitir-um-cupom-fiscal-nfce-em-segundos-p...,2025-02-15
255,3340,True,Guia completo passo a passo - Como Baixar e In...,"<p data-start=""248"" data-end=""657"">Se você est...",NaN,2025-02-17,c089bde9-1a56-435f-918a-5bcf422a224b,https://otimizeseunegocio.com/nota-fiscal/guia...,https://otimizeseunegocio.com/wp-content/uploa...,Captura de tela 2025-02-17 175634,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,guia-completo-passo-a-passo-como-baixar-e-inst...,2025-02-28
256,3359,True,"ATENÇÃO, MEI! Sua Nota Fiscal Pode Ser Bloquea...","<h2 data-pm-slice=""1 1 []"">Atenção!</h2>\nSe v...",NaN,2025-03-20,478ee0ac-f8e0-4a3a-a5fc-6e792d299ce0,https://otimizeseunegocio.com/nota-fiscal/aten...,https://otimizeseunegocio.com/wp-content/uploa...,crt 4,...,NaN,NaN,publish,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,atencao-mei-sua-nota-fiscal-pode-ser-bloqueada...,2025-03-20
257,3379,True,"Abri o MEI, e Agora? Tudo o Que Você Precisa S...","<p data-pm-slice=""1 1 []"">Se você acabou de da...",NaN,2025-04-16,1ee4abbd-899c-413e-8734-3aba748056e0,https://otimizeseunegocio.com/nota-fiscal/abri...,https://otimizeseunegocio.com/wp-content/uploa...,thumb tudo sobre mei_abril_2025,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,abri-o-mei-e-agora-tudo-o-que-voce-precisa-sab...,2025-04-16
258,3386,True,Crédito/ Empréstimo Consignado para CLT com FG...,"<h1 class="""" data-start=""214"" data-end=""274""><...",NaN,2025-04-17,4fa0cd78-38b3-48b2-a18b-d6023c6ff160,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,thumb emprestimo consignado CLT,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,credito-emprestimo-consignado-para-clt-com-fgt...,2025-04-17
259,3390,True,Erro ao Salvar Nota no Emissor Sebrae NFCe: Co...,"<p class="""" data-start=""112"" data-end=""482"">Se...",NaN,2025-05-07,a6cb5892-064a-43cd-8d32-c11b906c516a,https://otimizeseunegocio.com/nota-fiscal/erro...,https://otimizeseunegocio.com/wp-content/uploa...,thumb erro emitir nfce sebrae,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,erro-ao-salvar-nota-no-emissor-sebrae-nfce-com...,2025-05-07
260,3398,True,Como aumentar / expandir Fotos com Inteligênci...,"<h1 class="""" data-start=""302"" data-end=""387""><...",NaN,2025-05-09,9ce09f79-0f96-4783-9278-b31e8f155e32,https://otimizeseunegocio.com/tutoriais/como-a...,https://otimizeseunegocio.com/wp-content/uploa...,Captura de tela 2025-05-09 193944,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-aumentar-expandir-fotos-com-inteligencia-...,2025-05-09
261,3409,True,Como Emitir uma NFC-e Usando o Emissor Gratuit...,"<h1 class="""" data-start=""205"" data-end=""284""><...",NaN,2025-05-13,e055da09-f1f5-43aa-b585-d6b4ec9bdf17,https://otimizeseunegocio.com/uncategorized/co...,https://otimizeseunegocio.com/wp-content/uploa...,x-KWKhP5RVitJ6zRZWBE2A|Captura de tela 2025-05...,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-emitir-uma-nfc-e-usando-o-emissor-gratuit...,2025-05-13
262,3416,True,Como Emitir Nota Fiscal Eletrônica pelo Celula...,"<p class="""" data-start=""388"" data-end=""765"">Se...",NaN,2025-05-21,f05e526b-2af8-49ef-8c0f-4fb6dd990090,https://otimizeseunegocio.com/nota-fiscal/como...,https://otimizeseunegocio.com/wp-content/uploa...,Captura de tela 2025-05-20 204744,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,como-emitir-nota-fiscal-eletronica-pelo-celula...,2025-05-28
263,3421,True,MEI tem direito a seguro desemprego? Descubra ...,"<p data-start=""270"" data-end=""658"">Muitos bras...",NaN,2025-05-28,3183cecd-c0b3-4cc8-b591-9d1534553337,https://otimizeseunegocio.com/dicas-hacks/mei-...,https://otimizeseunegocio.com/wp-content/uploa...,XQoCY1ILRXqjL9I8tPU8XQ,...,NaN,NaN,publish,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,mei-tem-direito-a-seguro-desemprego-descubra-o...,2025-05-28

Número de linhas no df_check_true: 22

In [ ]:
df_check_true.to_csv('posts_formatação_completa.csv', index=False)
print("DataFrame com iframe exportado para 'posts_formatação_completa.csv'")

DataFrame com iframe exportado para 'posts_formatação_completa.csv'

## Imagens

In [ ]:
# tratar imagens
# imagem destacada: coletar da coluna Featured_image
# imgagens do texto: parsear e coletar imagem do imageURL ignorando a imagem destacadas
# agrupar imageTitle

In [ ]:
# posts relacionados: Coluna _jetpack_related_posts_cache

In [ ]:
# redirecionamento 301: trazer