base de dados:
- dados dos posts wordpress (pre-migração)
- dados dos posts wix (pós-migração)

Como organizar os dados de forma que facilite a migração e tratamento entre as duas plataformas?

- usar duckdb para compilar os dados relacionado a cada post
- importar dados brutos do wordpress pelo csv
- importar dados atuais do wix
- criar colunar auxiliares para tratamentos


checklist:
- Decidir como executar processo de etl
    - qual estrutura de dados vai ser usada
        - tratamento de dados: duck e dict
        - armazenamento de dados: duck
    - qual Limites de transação de cada api?

- download de posts wix: Completo
    - listar todos posts_id's: completo
    - baixar todos os posts: completo

- converter posts para dict: feito
- coletar versão funcional do main com wallace: feito

- converter post html para rico_documento wix: revisar
    - tags's de titulos
    - tags's de texto
    - tag's de video
    - tag's de decoração
    - tag's de imagens
    - scripts
-

# Posts Wordpress

In [1]:
import pandas as pd
import os
import json

In [2]:
caminho_csv_wordpress = './docs/Posts-Export-2025-July-25-1838.csv'
caminho_posts_wix = './data/posts/'
mapeamento = './data/wix_wordpress_mapping.json'


df = pd.read_csv(caminho_csv_wordpress)
df.head(10)

,ID,check de edição,Title,Content,Excerpt,Date,PostType,Coluna 1,Permalink,ImageURL,...,AuthorLastName,Slug,Format,Template,Parent,ParentSlug,Order,CommentStatus,PingStatus,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,debito-ou-credito,NaN,NaN,NaN,NaN,NaN,open,open,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,NaN,NaN,NaN,NaN,NaN,open,open,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,NaN,NaN,NaN,NaN,NaN,open,open,2018-07-12
5,47,False,NFCe: posso emitir na minha impressora fiscal?,"<span style=""font-weight: 400;"">O ECF - Emisso...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/legislacao/nfce-...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,nfce-posso-emitir-na-minha-impressora-fiscal,NaN,NaN,NaN,NaN,NaN,open,open,2018-03-13
6,51,False,NF-e e NFC-e: sou obrigado emitir?,"<span style=""font-weight: 400;"">Você abriu sua...",NaN,2018-03-01,post,NaN,https://otimizeseunegocio.com/legislacao/nf-e-...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,nf-e-e-nfc-e-sou-obrigado-emitir,NaN,NaN,NaN,NaN,NaN,open,open,2019-05-10
7,89,False,Como emitir uma nota fiscal eletrônica utiliza...,"<iframe src=""https://www.youtube.com/embed/KdK...",NaN,2018-03-15,post,NaN,https://otimizeseunegocio.com/legislacao/como-...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,como-emitir-uma-nota-fiscal-eletronica-utiliza...,NaN,NaN,NaN,NaN,NaN,open,open,2018-03-17
8,94,False,[Planilha Financeira] Se você cuida bem das su...,"<iframe src=""https://www.youtube.com/embed/ta_...",NaN,2018-03-17,post,NaN,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,movimento-de-caixa-planilha-gratis,NaN,NaN,NaN,NaN,NaN,open,open,2018-03-17
9,98,False,Como instalar o Emissor Gratuito?,<h4>Antes que você veja sobre o emisssor gratu...,NaN,2018-03-24,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,como-instalar-o-emissor-gratuito,NaN,NaN,NaN,NaN,NaN,open,open,2020-09-30

In [3]:
# Renomear colunas do DataFrame
# 'coluna 1' -> 'ID_wix'
# 'ID' -> 'ID_Wordpress'
if 'Coluna 1' in df.columns and 'ID' in df.columns:
    df.rename(columns={'Coluna 1': 'ID_wix', 'ID': 'ID_Wordpress'}, inplace=True)

df.head()

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,PostType,ID_wix,Permalink,ImageURL,...,AuthorLastName,Slug,Format,Template,Parent,ParentSlug,Order,CommentStatus,PingStatus,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,debito-ou-credito,NaN,NaN,NaN,NaN,NaN,open,open,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,NaN,NaN,NaN,NaN,NaN,open,open,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,post,NaN,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,NaN,NaN,NaN,NaN,NaN,open,open,2018-07-12

In [4]:
df1 = df

In [5]:
# Diretório onde os arquivos JSON estão localizados
posts_dir = '/content/posts/' # Corrected path to posts directory
mapeamento_path = '/content/wix_wordpress_mapping.json' # Corrected path to mapping file

# Load the mapping from the JSON file
try:
    with open(mapeamento_path, 'r') as f:
        wix_wordpress_mapping = json.load(f)
except (IOError, json.JSONDecodeError) as e:
    print(f"Erro ao carregar o arquivo de mapeamento {mapeamento_path}: {e}")
    wix_wordpress_mapping = {} # Initialize as empty dict if error occurs

def find_and_update_wix_id(row):
    id_wordpress = str(row['ID_Wordpress']) # Convert to string to match keys in mapping
    # Look up the ID_wix in the mapping
    wix_id = wix_wordpress_mapping.get(id_wordpress)
    return wix_id

# Iterar sobre cada linha do DataFrame e atualizar a coluna 'ID_wix'
df1['ID_wix'] = df1.apply(find_and_update_wix_id, axis=1)

print("DataFrame atualizado:")
display(df1.head())

Erro ao carregar o arquivo de mapeamento /content/wix_wordpress_mapping.json: [Errno 2] No such file or directory: '/content/wix_wordpress_mapping.json'
DataFrame atualizado:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,PostType,ID_wix,Permalink,ImageURL,...,AuthorLastName,Slug,Format,Template,Parent,ParentSlug,Order,CommentStatus,PingStatus,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,post,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,debito-ou-credito,NaN,NaN,NaN,NaN,NaN,open,open,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,post,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,post,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,NaN,NaN,NaN,NaN,NaN,open,open,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,post,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,NaN,NaN,NaN,NaN,NaN,open,open,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,post,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,...,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,NaN,NaN,NaN,NaN,NaN,open,open,2018-07-12

In [6]:
df2 = df1

In [7]:
# Identify columns with only empty values or a single unique value
cols_to_drop_identified = []
for col in df2.columns:
    # Drop NaN values before checking for unique values
    unique_values = df2[col].dropna().unique()
    if len(unique_values) <= 1:
        cols_to_drop_identified.append(col)

print("Colunas com apenas campos vazios ou um único valor:")
for col in cols_to_drop_identified:
    print(f"- {col}")

Colunas com apenas campos vazios ou um único valor:
- Excerpt
- PostType
- ID_wix
- AttachmentURL
- _rdscriptcontenttop
- _rdscriptcontentbottom
- _rdscriptcontentinhead
- _rdscriptcontentinfooter
- _wp_page_template
- site_sidebar_layout
- site_content_layout
- theme_transparent_header_meta
- _elementor_edit_mode
- _elementor_template_type
- _elementor_pro_version
- _wpas_done_all
- _pingme
- _encloseme
- ast_site_content_layout
- site_content_style
- site_sidebar_style
- _elementor_controls_usage
- amp_status
- _et_pb_use_builder
- _et_pb_old_content
- _jetpack_memberships_contains_paid_content
- Format
- Template
- Parent
- ParentSlug
- Order
- CommentStatus
- PingStatus

In [8]:
colunas_para_remover = ['Format', 'Template', 'Parent', 'ParentSlug', 'CommentStatus', 'PingStatus', 'PostType', 'AttachmentURL', '_rdscriptcontenttop', '_rdscriptcontentbottom', '_rdscriptcontentinhead',
                        '_rdscriptcontentinfooter', '_wp_page_template', 'site_sidebar_layout', 'site_content_layout', 'theme_transparent_header_meta', '_elementor_edit_mode', '_elementor_template_type', '_elementor_pro_version', '_wpas_done_all', '_pingme', '_encloseme', 'ast_site_content_layout', 'site_content_style', 'site_sidebar_style', '_elementor_controls_usage', 'amp_status', '_et_pb_use_builder', '_et_pb_old_content', '_jetpack_memberships_contains_paid_content', 'Order']

# Filter out columns that do not exist in the DataFrame
cols_to_drop_existing = [col for col in colunas_para_remover if col in df2.columns]

df2 = df2.drop(columns=cols_to_drop_existing)
print("DataFrame após remover colunas irrelevantes:")
display(df2.head())

DataFrame após remover colunas irrelevantes:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cash only|Ingredientes de uma pizza,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Multas são caras|Nazaré confusa,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,Problemas com o sistema,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,Certificado digital|Certificado digital e token,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,2018-07-12

In [9]:
# Filter posts where status is not 'publish'
posts_not_published = df2[df2['Status'] != 'publish']

print("Posts com status diferente de 'publish':")
display(posts_not_published)

Posts com status diferente de 'publish':

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
52,629,False,[Dúvida] O MEI precisa de Contador?,"Afinal, o Microempreendedor Individual precisa...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=629,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2019-10-21
67,727,False,Como emitir uma Nota Fiscal no emissor gratuit...,"<img class=""alignnone wp-image-417 aligncenter...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=727,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2020-05-14
73,803,False,Como desabilitar um produto no Easygestor,Vá no Aplicativo de compras\n\n&nbsp;,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=803,NaN,NaN,...,NaN,NaN,draft,4,vitor,vitor@ebi.com.br,Vitor,Alves,NaN,2020-08-04
76,896,False,Descubra como Agendar mensagens pela Whatsapp,Quem é,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=896,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2020-09-08
83,1024,False,Tabela do Simples Nacional Atualizada 2020,NaN,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1024,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2020-11-03
91,1682,False,Tabela De Atividades Permitidas MEI 2021,<h4>Se você acabou de se tornar <strong>MEI</s...,Descubra aqui quais atividades o MEI pode exercer,2021-05-06,None,https://otimizeseunegocio.com/legislacao/tabel...,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,private,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,tabela-de-atividades-permitidadas-mei-2021,2021-09-08
97,1812,False,COMO ABRIR UM MEI GRÁTIS,"<span style=""font-weight: 400;"">Abrir e gerenc...",NaN,2021-12-21,None,https://otimizeseunegocio.com/?p=1812,https://otimizeseunegocio.com/wp-content/uploa...,MEI-Microempreendedor-Individual,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-03-23
106,1960,False,Teste,NaN,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1960,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-08-16
107,1962,False,CLT e MEI: é possivel ser MEI e ter a carteira...,NaN,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1962,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-08-17
111,1992,False,COMPRA DE SEGUIDORES É UM RISCO?,"<span style=""font-weight: 400"">Parece uma ótim...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=1992,NaN,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,1970-01-01
120,2159,False,CERTIFICADO DIGITAL: PRINCIPAIS RISCOS E CUIDA...,"<span style=""font-weight: 400""><img class=""ali...",NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=2159,https://otimizeseunegocio.com/wp-content/uploa...,NaN,...,NaN,NaN,draft,13,robertalavareda,roberta@otimizeseunegocio.com,Roberta,Lavareda,NaN,2022-10-27
130,2333,False,Recuperando Arquivos do PC e Pendrive: Um Guia...,&nbsp;\n\nEm um mundo onde a tecnologia desemp...,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=2333,NaN,NaN,...,NaN,NaN,draft,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,NaN,2023-08-25
137,2398,False,Curso de Marketing Digital com Super desconto ...,O Canal Otimize seu Negócio está chegando a 20...,NaN,1970-01-01,None,https://otimizeseunegocio.com/?p=2398,https://otimizeseunegocio.com/wp-content/uploa...,Imagem do WhatsApp de 2023-09-19 à(s) 12.51.49,...,NaN,NaN,draft,17,Paola Queiroz,mkt@easygestor.com,Paola,Queiroz,NaN,2023-09-19
226,3114,False,Totem Especialista Belém,"<script>!function(window){const host=""https://...",NaN,2024-10-02,None,https://otimizeseunegocio.com/?p=3114,NaN,NaN,...,NaN,NaN,draft,4,vitor,vitor@ebi.com.br,Vitor,Alves,totem-especialista-belem,2024-10-02

In [10]:
# Remove posts with status other than 'publish' from df2
df2 = df2.drop(posts_not_published.index)

print("DataFrame df2 após remover posts não publicados:")
display(df2.head())
print(f"\nNúmero de linhas em df2 após a remoção: {len(df2)}")

DataFrame df2 após remover posts não publicados:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cash only|Ingredientes de uma pizza,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Multas são caras|Nazaré confusa,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,Problemas com o sistema,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,Certificado digital|Certificado digital e token,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,2018-07-12

Número de linhas em df2 após a remoção: 250

In [11]:
print(f"Número de colunas em df2: {len(df2.columns)}")
print("\nColunas em df2:")
for col in df2.columns:
    print(f"- {col}")

Número de colunas em df2: 37

Colunas em df2:
- ID_Wordpress
- check de edição
- Title
- Content
- Excerpt
- Date
- ID_wix
- Permalink
- ImageURL
- ImageTitle
- ImageCaption
- ImageDescription
- ImageAltText
- ImageFeatured
- Categorias
- Tags
- highlight
- highlight_list
- _jetpack_related_posts_cache
- _last_editor_used_jetpack
- _elementor_version
- ekit_post_views_count
- astra_migrate_meta_layouts
- _elementor_data
- dsq_thread_id
- _elementor_page_assets
- _wp_old_slug
- _wp_old_date
- _elementor_css
- Status
- AuthorID
- AuthorUsername
- AuthorEmail
- AuthorFirstName
- AuthorLastName
- Slug
- PostModifiedDate

In [12]:
df3 = df2

In [13]:
colunas_para_remover = ['Format', 'Template', 'Parent', 'ParentSlug', 'CommentStatus', 'PingStatus', 'PostType', 'AttachmentURL', '_rdscriptcontenttop', '_rdscriptcontentbottom', '_rdscriptcontentinhead',
                        '_rdscriptcontentinfooter', '_wp_page_template', 'site_sidebar_layout', 'site_content_layout', 'theme_transparent_header_meta', '_elementor_edit_mode', '_elementor_template_type',
                        '_elementor_pro_version', '_wpas_done_all', '_pingme', '_encloseme', 'ast_site_content_layout', 'site_content_style', 'site_sidebar_style', '_elementor_controls_usage', 'amp_status',
                        '_et_pb_use_builder', '_et_pb_old_content', '_jetpack_memberships_contains_paid_content', 'Order', '_jetpack_related_posts_cache', '_last_editor_used_jetpack', '_elementor_version', 'ekit_post_views_count', 'astra_migrate_meta_layouts', '_elementor_page_assets', '_elementor_css']

# Filter out columns that do not exist in the DataFrame
cols_to_drop_existing = [col for col in colunas_para_remover if col in df2.columns]

df2 = df2.drop(columns=cols_to_drop_existing)
print("DataFrame após remover colunas irrelevantes:")
display(df3.head())

DataFrame após remover colunas irrelevantes:

,ID_Wordpress,check de edição,Title,Content,Excerpt,Date,ID_wix,Permalink,ImageURL,ImageTitle,...,_wp_old_date,_elementor_css,Status,AuthorID,AuthorUsername,AuthorEmail,AuthorFirstName,AuthorLastName,Slug,PostModifiedDate
0,21,True,Débito ou crédito: entenda as vantagens e desv...,"<img class=""size-large wp-image-23 aligncenter...",NaN,2018-02-20,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cartões|credit-card-processing-definitions|Cal...,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,debito-ou-credito,2019-02-14
1,30,False,Qual o seu preço? Aprenda este método de calcu...,"<p style=""text-align: center;""><em><strong>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Cash only|Ingredientes de uma pizza,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-aprenda-este-metodo-de-calcul...,2018-08-08
2,34,False,Qual o seu preço? Parte 2: Aprenda de uma vez ...,"<p style=""text-align: center;""><strong><em>Est...",NaN,2018-02-26,None,https://otimizeseunegocio.com/saude-financeira...,https://otimizeseunegocio.com/wp-content/uploa...,Multas são caras|Nazaré confusa,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,qual-o-seu-preco-parte-2-aprenda-de-uma-vez-po...,2018-08-08
3,37,False,5 motivos para NÃO usar um emissor grátis de n...,"<span style=""font-weight: 400;"">Uma das obriga...",NaN,2018-02-26,None,https://otimizeseunegocio.com/gestao-organizac...,https://otimizeseunegocio.com/wp-content/uploa...,Problemas com o sistema,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-nao-usar-um-emissor-gratis-de-n...,2018-04-13
4,40,False,5 motivos para preferir o certificado A1 (e nã...,"<h2 style=""text-align: center;"">[button type=""...",NaN,2018-02-26,None,https://otimizeseunegocio.com/legislacao/5-mot...,https://otimizeseunegocio.com/wp-content/uploa...,Certificado digital|Certificado digital e token,...,NaN,NaN,publish,4,vitor,vitor@ebi.com.br,Vitor,Alves,5-motivos-para-preferir-o-certificado-a1-e-nao...,2018-07-12

# Duckdb

In [14]:
import duckdb

# Connect to an in-memory database
# con = duckdb.connect(database=':memory:', read_only=False)

# Or connect to a file
con = duckdb.connect(database='data/migration.duckdb', read_only=False)

# Create a sample table for demonstration
con.execute("CREATE TABLE items(id INTEGER, name VARCHAR);");
con.execute("INSERT INTO items VALUES (1, 'Laptop'), (2, 'Mouse'), (3, 'Keyboard');");

# Query to show columns from a specific table
table_name = 'items'

# Method 1: Using DESCRIBE
print(f"Columns in '{table_name}' using DESCRIBE:")
describe_result = con.execute(f"DESCRIBE {table_name}").fetchall()
for col in describe_result:
    print(f"- {col[0]} ({col[1]})")

print('\n' + '-'*30 + '\n')

# Method 2: Using PRAGMA table_info
print(f"Columns in '{table_name}' using PRAGMA table_info:")
pragma_result = con.execute(f"PRAGMA table_info('{table_name}')").fetchall()
# The result format is: (column_id, column_name, column_type, nullable, default_value, is_primary_key)
for col in pragma_result:
    print(f"- {col[1]} ({col[2]})")


# Close the connection
con.close()

CatalogException: Catalog Error: Table with name "items" already exists!

In [ ]:
import duckdb
import json

# 1. Carregar o richContent do arquivo JSON
with open('./data/post_exemples/0e4b70b8-e052-4260-9df2-c2516c6b9685.json') as f:
    post_data = json.load(f)

# Converte o dicionário 'richContent' para uma string JSON
rich_content_string = json.dumps(post_data['richContent'])
post_id = post_data['id']
# Suponha que temos um conteúdo HTML para este post
html_content = "<html><body><h1>Título do Post</h1><p>Este é o conteúdo HTML...</p></body></html>"

# 2. Conectar ao DuckDB e criar a tabela
con = duckdb.connect(database=':memory:') # Usando banco de dados em memória para o exemplo

con.execute("""
CREATE TABLE wix_posts (
    id VARCHAR PRIMARY KEY,
    html_content TEXT,
    rich_content JSON
);
""")

# 3. Inserir os dados na tabela
con.execute(
    "INSERT INTO wix_posts (id, html_content, rich_content) VALUES (?, ?, ?)",
    [post_id, html_content, rich_content_string]
)

# 4. Consultar e extrair dados do JSON
# Exemplo: Extrair o tipo do primeiro nó dentro de 'richContent'
result = con.execute("""
SELECT
    id,
    html_content,
    json_extract(rich_content, '$.nodes[0].type') AS first_node_type
FROM wix_posts;
""").fetchone()

print(result)
# Saída esperada: ('0e4b70b8-e052-4260-9df2-c2516c6b9685', '<html>...</html>', 'PARAGRAPH')

An error occurred: Catalog Error: Table with name my_table does not exist!
Did you mean "pg_tables"?

LINE 1: SELECT * FROM "my_table" LIMIT 5
                      ^

# Tratamentos

In [ ]:
# tratar imagens
# imagem destacada: coletar da coluna Featured_image
# imgagens do texto: parsear e coletar imagem do imageURL ignorando a imagem destacadas
# agrupar imageTitle

In [ ]:
# posts relacionados: Coluna _jetpack_related_posts_cache